services:
  server:
    build: .
    container_name: server
    ports:
      - "8080:8080"
    networks:
      - app_network

  nginx:
    image: nginx:1.27
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
